# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTK_NET_PHYLIB)		+= mtk-phy-lib.o
obj-$(CONFIG_MEDIATEK_GE_PHY)		+= mtk-ge.o
obj-$(CONFIG_MEDIATEK_GE_SOC_PHY)	+= mtk-ge-soc.o
mtk-ge-soc-objs	+= mtk-ge-soc.o
mtk-ge-soc-objs	+= airoha-phy-lib.o an7523.o an7581.o
