# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_AIROHA_LDDLA_PHY) += airoha_lddla.o

airoha_lddla-y := airoha_lddla_core.o
airoha_lddla-$(CONFIG_EN7570_PHY) += en7570_adcloop.o
airoha_lddla-$(CONFIG_EN7570_PHY) += en7570_ddmi.o
airoha_lddla-$(CONFIG_EN7570_PHY) += en7570_main.o
airoha_lddla-$(CONFIG_EN7570_PHY) += en7570_txrx.o
airoha_lddla-$(CONFIG_EN7571_PHY) += en7571_adcloop.o
airoha_lddla-$(CONFIG_EN7571_PHY) += en7571_ddmi.o
airoha_lddla-$(CONFIG_EN7571_PHY) += en7571_main.o
airoha_lddla-$(CONFIG_EN7571_PHY) += en7571_txrx.o
airoha_lddla-$(CONFIG_EN7572_PHY) += en7572_ddmi.o
airoha_lddla-$(CONFIG_EN7572_PHY) += en7572_loop.o
airoha_lddla-$(CONFIG_EN7572_PHY) += en7572_main.o
