/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* PSE ethtool netlink definitions - OpenWrt backport for 6.12 */

#ifndef _UAPI_LINUX_ETHTOOL_NETLINK_GENERATED_H
#define _UAPI_LINUX_ETHTOOL_NETLINK_GENERATED_H

enum ethtool_pse_event {
	ETHTOOL_PSE_EVENT_OVER_CURRENT = 1,
	ETHTOOL_PSE_EVENT_OVER_TEMP = 2,
	ETHTOOL_C33_PSE_EVENT_DETECTION = 4,
	ETHTOOL_C33_PSE_EVENT_CLASSIFICATION = 8,
	ETHTOOL_C33_PSE_EVENT_DISCONNECTION = 16,
	ETHTOOL_PSE_EVENT_OVER_BUDGET = 32,
	ETHTOOL_PSE_EVENT_SW_PW_CONTROL_ERROR = 64,
};

enum {
	ETHTOOL_A_PSE_NTF_HEADER = 1,
	ETHTOOL_A_PSE_NTF_EVENTS,
	__ETHTOOL_A_PSE_NTF_CNT,
	ETHTOOL_A_PSE_NTF_MAX = (__ETHTOOL_A_PSE_NTF_CNT - 1)
};

enum {
	ETHTOOL_A_PSE_NTF_EVT_UNSPEC,
	ETHTOOL_A_PSE_NTF_EVT_INDEX,
	__ETHTOOL_A_PSE_NTF_EVT_CNT,
	ETHTOOL_A_PSE_NTF_EVT_MAX = (__ETHTOOL_A_PSE_NTF_EVT_CNT - 1)
};

#endif /* _UAPI_LINUX_ETHTOOL_NETLINK_GENERATED_H */
