/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_XPON_H
#define _UAPI_LINUX_XPON_H

#define XPON_GENL_NAME		"xpon"
#define XPON_GENL_VERSION	1

enum xpon_mode {
	XPON_MODE_GPON = BIT(1),	/* ITU-T G.984 (2.5Gbps RX / 1.2Gbps TX) */
	XPON_MODE_EPON = BIT(2),	/* IEEE 802.3ah (1Gbps) */
	XPON_MODE_XEPON = BIT(3),	/* IEEE 802.3av (10G) */
	XPON_MODE_XGPON = BIT(4),	/* ITU-T G.987 (10Gbps RX / 2.5Gbps TX) */
	XPON_MODE_XGSPON = BIT(5),	/* ITU-T G.9807.1 (10Gbps) */
	XPON_MODE_NGPON2 = BIT(6),	/* ITU-T G.989 (10Gbps per channel) */
	XPON_MODE_25GSPON = BIT(7),	/* 25GS-PON MSA specification (25Gbps) */
	XPON_MODE_50GPON = BIT(8),	/* ITU-T G.9804 (50Gbps) */
	XPON_MODE_25GEPON = BIT(9),	/* IEEE 802.3ca (25Gbps) */
	XPON_MODE_50GEPON = BIT(10),	/* IEEE 802.3ca (50Gbps) */

	__XPON_MODE_MAX,
};
#define XPON_MODE_MAX (__XPON_MODE_MAX - 1)

enum xpon_registration_state {
	XPON_REGISTRATION_DOWN,
	XPON_REGISTRATION_DISCOVERY,
	XPON_REGISTRATION_REGISTERING,
	XPON_REGISTRATION_OPERATIONAL,
};

enum xpon_cmd {
	XPON_CMD_UNSPEC,
	XPON_CMD_GET,
	XPON_CMD_GET_CAPS,
	XPON_CMD_GET_STATE,
	XPON_CMD_SET_MODE,
	XPON_CMD_EVENT,

	__XPON_CMD_MAX,
};
#define XPON_CMD_MAX (__XPON_CMD_MAX - 1)

enum xpon_attr {
	XPON_ATTR_UNSPEC,
	XPON_ATTR_IFINDEX,
	XPON_ATTR_MODE,
	XPON_ATTR_AVAILABLE_MODES,
	XPON_ATTR_REGISTRATION,
	XPON_ATTR_CARRIER,
	XPON_ATTR_SIGNAL_DETECT,
	XPON_ATTR_LOS,
	XPON_ATTR_CHANGED,

	__XPON_ATTR_MAX,
};
#define XPON_ATTR_MAX (__XPON_ATTR_MAX - 1)

#endif /* _UAPI_LINUX_XPON_H */
